### ISSUE TITLE
MagSensor Position

### ISSUE THREAD

**Issue by degeflija** [larus-breeze/hw_sensor#1]
Max, kannst du den MagSensor aus der Ecke rausholen und ein wenig besser und freier einbauen ?
Ich vermute, dass das RJ45 Gehäuse da ein wenig abschirmt.

Außerdem sollten wir sicherstellen, dass alle Gehäuseschrauben aus Messing sind.

**Comment by MaxBaex** [comment]
Die RJ45 Abschirmung ist nicht magnetisch, das hat Klaus überprüft.   Ich habe den Kompass bewusst weit in diese Ecke, möglichst weit von Spannungswandlern und größeren Strömen platziert. 

Die Gehäuse, ich ich zusammengeschraubt habe, habe ich mit Messingschrauben versehen.  Da sollte kein feromagnetisches Material dran sein.

**Comment by MaxBaex** [comment]
Ist in der neuen Version berücksichtigt.
