### ISSUE TITLE
DGNSS / Pixhawk-Connector: RX TX vertauscht

### ISSUE THREAD

**Issue by realtimepeople** [larus-breeze/hw_sensor#2]
Siehe Titel.
Abhilfe: Das Kabel patchen.

**Comment by MaxBaex** [comment]
https://raw.githubusercontent.com/pixhawk/Pixhawk-Standards/master/DS-009%20Pixhawk%20Connector%20Standard.pdf

**Comment by MaxBaex** [comment]
For usage with: https://www.ardusimple.de/product/simplertk2b-heading-basic-starter-kit-ip67/
